include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    flutter_style_todos: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - lib/**/generated/** # Exclude all generated filed that you have no control over
    - lib/**/_generated/** # Exclude all generated filed that you have no control over

formatter:
  page_width: 120
  trailing_commas: preserve